trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-dev

steps:
# https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
- task: Maven@3
  inputs:
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.8'
    goals: 'verify'
    options: '-Dcpi.host.tmn=$(dev-host-tmn) -Dcpi.basic.userid=$(dev-user) -Dcpi.basic.password=$(dev-password) -Dcpi.host.oauth=$(dev-oauth-host) -Dcpi.oauth.clientid=$(dev-client-id) -Dcpi.oauth.clientsecret=$(dev-client-secret)'
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker
  # Lite version
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub engswee'
    repository: 'engswee/flashpipe'
    command: 'buildAndPush'
    Dockerfile: 'src/main/docker/lite.Dockerfile'
    buildContext: '.'
    tags: 2.1.0-lite  # FLASHPIPE_VERSION
# Full version with Maven
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub engswee'
    repository: 'engswee/flashpipe'
    command: 'buildAndPush'
    Dockerfile: 'src/main/docker/Dockerfile'
    buildContext: '.'
    tags: 2.1.0  # FLASHPIPE_VERSION